### PR TITLE
Nested selector support

### PR DESCRIPTION
**Pull request by meetjey**
Hi !

Just add nested selector support for #27 issue.

Thanks for your plugin !

### CODE REVIEW

**Comment by meetjey** [comment]
@pranaygp does this meet your expectations?

**Comment by pranaygp** [comment]
Sorry @meetjey, I completely missed the notification for this PR.

Thanks for the ping 😁

**Comment by pranaygp** [comment]
Could you add an example of the '&' nested selector here so it's easy to manually test
https://github.com/pranaygp/vscode-css-peek/blob/master/client/test/test_files/example.scss

Bonus points if you extend the automated unit tests to test the findSelectoe method (we currently don't have tests for it) including your update 🙌🙌

**Comment by pranaygp** [comment]
Thanks for the contribution @meetjey 
I've gone ahead and implemented this more reliably in the latest 4.0.0+ while referencing your code. I also added a test case. I did it using recursion so it should support infinite nests and the code is a bit smaller. 

If you want to give it a look and see if I missed something, please let me know

**Pull request closed without merging**
